### ISSUE TITLE
Add a sign-up page for users with an invite

### ISSUE THREAD

**Issue by prgu6170** [The-Encryption-Compendium/the-encryption-compendium#15]
Currently, there is no sign-up page for users with an invite. Page must validate the unique-code and allow user to sign up to start contributing to the project.

**Comment by kernelmethod** [comment]
Fixed by e986e0af2b47b5c1e8bc523e39a6e51f6fdfc571 - 91f6a3e5b75f4b64aaef0f1f4ed79db29f21983b.
