### ISSUE TITLE
Check password strength before changing user password

### ISSUE THREAD

**Issue by prgu6170** [The-Encryption-Compendium/the-encryption-compendium#23]
**Is your feature request related to a problem? Please describe.**
Currently users can change their password to as small as just a letter.

**Describe the solution you'd like**
Check if the password is strong before changing the password for the user.

**Comment by kernelmethod** [comment]
This is actually almost completely implemented by the presence of `django.contrib.auth.password_validation.CommonPasswordValidator` in `AUTH_PASSWORD_SETTINGS` in `settings.py` ([code](https://github.com/The-Encryption-Compendium/the-encryption-compendium/blob/2fbccd01e2d235e39e602c0b7644ff7f3f738c5c/src/encryption_compendium/settings.py#L157)). As long as the password change form runs `validate_password` ([docs](https://docs.djangoproject.com/en/3.0/topics/auth/passwords/#django.contrib.auth.password_validation.validate_password)) before you change the user's password, you'll be able to determine whether or not the user has a password that's too common.

I have [some tests](https://github.com/The-Encryption-Compendium/the-encryption-compendium/blob/2fbccd01e2d235e39e602c0b7644ff7f3f738c5c/src/encryption_compendium/tests/test_settings.py#L35) to check that `validate_password` is performing all of the checks we want it to, but I just realized it doesn't check that we're actually running `CommonPasswordValidator`. I've added that test and pushed it to master as commit e9a4beb85ba60812dd9df84bb0a6dc949985f8db.
