### ISSUE TITLE
Add "authors" field to CompendiumEntry

### ISSUE THREAD

**Issue by kernelmethod** [The-Encryption-Compendium/the-encryption-compendium#33]
Add a new `authors` field to the `CompendiumEntry` model. This should almost certainly be created as a `ManyToManyField` in the model (since one entry can have multiple authors, and one author can have written multiple entries).

**Comment by prgu6170** [comment]
100fd9e2ea0b2c2769c2429d224f684f0f3a154f and ad1bc80b26253557918b708625b750caa696b485
