### ISSUE TITLE
Improve test coverage for the research_assistant app's views

### ISSUE THREAD

**Issue by kernelmethod** [The-Encryption-Compendium/the-encryption-compendium#36]
As of e8190d3874622ee979164052e6d4cafa7709fbda, `src/research_assistant/views.py` has pretty poor test coverage ([71.20% view codecov](https://codecov.io/gh/The-Encryption-Compendium/the-encryption-compendium/src/e8190d3874622ee979164052e6d4cafa7709fbda/src/research_assistant/views.py)). The follow views seem to be heavily undertested:

- [`research_dashboard`](https://codecov.io/gh/The-Encryption-Compendium/the-encryption-compendium/src/e8190d3874622ee979164052e6d4cafa7709fbda/src/research_assistant/views.py#L134)
- [`research_list_my_entries`](https://codecov.io/gh/The-Encryption-Compendium/the-encryption-compendium/src/e8190d3874622ee979164052e6d4cafa7709fbda/src/research_assistant/views.py#L193)
- [`research_edit_entries`](https://codecov.io/gh/The-Encryption-Compendium/the-encryption-compendium/src/e8190d3874622ee979164052e6d4cafa7709fbda/src/research_assistant/views.py#L226)

The `sign_up` view [also needs a test](https://codecov.io/gh/The-Encryption-Compendium/the-encryption-compendium/src/e8190d3874622ee979164052e6d4cafa7709fbda/src/research_assistant/views.py#L95) for the case where `token` isn't passed as a URL parameter.

At the very least, the `research_dashboard` and `sign_up` views need better test coverage, and `research_edit_entries` should probably also have better coverage. We might be able to hold off on `research_list_my_entries` as that may be superseded by a different view in the not-too-distant future.

**Comment by prgu6170** [comment]
ede58e57035ad10aa5f58f6c5429d9ff83371978, 22c354be100967ef954d6fe9bbd84dfa41f8da5a, d7dc479b65578a91715e21617a87afe2a587899f, and 708981cc2f11608a602139df500432ed3960b15b
