### ISSUE TITLE
Fix broken site footer

### ISSUE THREAD

**Issue by kernelmethod** [The-Encryption-Compendium/the-encryption-compendium#39]
The footer doesn't actually appear at the bottom of the page, it seems to just get glued to the bottom of the viewport and ends up overlapping the page contents.

**Comment by prgu6170** [comment]
The issue still seen in new_entry form page.

**Comment by kernelmethod** [comment]
_Should_ be fixed by 7e8285f405170aab4aab0bf75ce08cea15e5c30a, but if you could check it out yourself before closing this issue that'd be great.

**Comment by prgu6170** [comment]
It works fine. However, the homepage sows the footer in middle of the window. I guess that could be taken up in another issue.
