### ISSUE TITLE
Clean up the settings page

### ISSUE THREAD

**Issue by kernelmethod** [The-Encryption-Compendium/the-encryption-compendium#40]
This is what the settings page currently looks like:

![settings](https://user-images.githubusercontent.com/17100608/75806266-94905b00-5d40-11ea-9ffa-2c5cdacf2820.png)

There are a couple of things that could be done to improve this:
- Add a margin between the top and bottom
- Reduce the width of the sidebar, emphasize the actual settings options instead

**Comment by prgu6170** [comment]
3b9bfcba627ad4d71ce075df47e9b0b4b6a7cd52
