### ISSUE TITLE
Refactoring Django apps

### ISSUE THREAD

**Issue by kernelmethod** [The-Encryption-Compendium/the-encryption-compendium#50]
Not an immediate necessity. However, I'm noticing that the functionality of our Django apps (currently: `public_view`, `research_assistant`, `research_settings`, and `search`) has over time overlapped and become a little murky. Ideally, each Django app should package together some logical subset of the functionality of the site. The way it's currently structured, we have situations where e.g. the `research_assistant` app is in charge of the `CompendiumEntry` model and friends, our custom `User` model, displaying all the views, for the research interface, etc.

I'm suggesting that we (eventually) reorganize our apps into the following apps:
- `users`: a Django app for our user model and some related forms (e.g. the login form). It should probably also be in charge of the `SignupToken` model.
- `entries`: an app that controls `CompendiumEntry` and related models in [src/research_assistant/models/compendium_models.py](https://github.com/The-Encryption-Compendium/the-encryption-compendium/blob/19a52ff193914f3a33700b2d9dd362fc66e4bd56/src/research_assistant/models/compendium_models.py), as well as forms related to these models.
- `search`: can probably stay in its current state ([src/search](https://github.com/The-Encryption-Compendium/the-encryption-compendium/tree/19a52ff193914f3a33700b2d9dd362fc66e4bd56/src/search)). This app exposes an API for searching the compendium database.
- `public_views`: again, can stay the same as [src/public_view](https://github.com/The-Encryption-Compendium/the-encryption-compendium/tree/19a52ff193914f3a33700b2d9dd362fc66e4bd56/src/public_view), which simply supports a bunch of different views for the site for non-members.
- `research_assistant`: after stripping out some functionality and placing it into the new `users` and `entries` apps, this app should just focus on the subset of views that will also be exposed to site members.
- `entry_management`: not completely sure if this should be its own app. The idea is that the `research_assistant` app does heavy work like parsing BibTeX files and controlling forms for managing compendium entries. This app would package together a large chunk of that functionality and serve as a library for managing the compendium (and hence the database). It could also be used for things like managing backups and logging.
- `utils`: there are some common useful classes (e.g. `encryption_compendium.widgets.IconTextInput`) being used in various places throughout the project. I'd suggest putting a lot of these utilities into their own app where they'd be easier to find and a little more organized. In addition, I've started writing a few class-based views throughout the project; a `utils` app could be a good place to store some generic views and mixins that can be subclassed by other apps.

I'm open to other suggestions for how to partition the apps.

**Comment by kernelmethod** [comment]
@prgu6170 let me know what you think of this. The refactoring shouldn't take too long but I'd want us to both be on board before making it since it'll significantly change the project structure.

**Comment by prgu6170** [comment]
I feel this is a good idea and is kind of important. About the `entry_management` app, I feel it is redundant. I think all the forms, views and models that control the entries, in any way like parsing BibTeX and storing them to the database, should go to `entries` app. The `research_assistant` app can be responsible for the views that the researchers can access. Let me know what you think about this.

**Comment by kernelmethod** [comment]
Fixed as of 304d62cd6a135cb99f0dd3e27c29ad6913ddf8b4
