### ISSUE TITLE
From a resource link: New tab on click

### ISSUE THREAD

**Issue by sbrunston** [The-Encryption-Compendium/the-encryption-compendium#64]
In order to keep people on the site, who may be researching multiple topics/resources, we might want to change the links to other sites to open in a new tab, rather than the current tab. 

Not sure if there is a way to globally apply something like this to only links outside the site or if it would need to be manual: 
<a href="someLink.html" target="_blank">
      <button>Visit my Github</button>
</a>

**Comment by prgu6170** [comment]
d7a61867ef47d29b2a4d0e2e4ce4029eb552a0c2

**Comment by prgu6170** [comment]
Now links will open in a new tab when external links from the websites are clicked.
